### ISSUE TITLE
Webpack error from Kibana 5.6.0

### ISSUE THREAD

**Issue by johnmcafee** [marghe943/kibanaChoroplethMap#2]
Hello, 

I resolved my previous issue regarding the properties file.  That was user error.
However, I am opening this issue because I have problem with Kibana when trying
to restart it.  I am using Kibana and Elasticsearch 5.6.0.  When I attempt to start Kibana,
I get the following error:
TypeError: __webpack_require__(1196).register is not a function. (In '__webpack_require__(1196).register(ChorMapProvider)', '__webpack_require__(1196).register' is undefined) (http://localhost:6070/bundles/kibana.bundle.js?v=8467:280)
Version: 5.6.0
Build: 8467
Error: TypeError: __webpack_require__(1196).register is not a function. (In '__webpack_require__(1196).register(ChorMapProvider)', '__webpack_require__(1196).register' is undefined) (http://localhost:6070/bundles/kibana.bundle.js?v=8467:280)
onerror@http://localhost:6070/bundles/commons.bundle.js?v=8467:83:8885

Any assistance with a solution would be greatly appreciated.

Thank you!

**Comment by marghe943** [comment]
Hi!

It was an error due to some Kibana changes (https://discuss.elastic.co/t/kibana-plugin-api-4-n-5-n-webpack-errors-when-compiling-tutorial-plugin/98228), plus I had to adjust something about filters. Now it works!
If you think of reinstalling the plugin from the beginning, remember to cancel the following lines from elasticsearch.yml (situated in "path_to_ES_folder/config" folder):

http.cors.enabled : true
http.cors.allow-origin: "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization, kbn-version"

In this period I'm very busy with studies, thus I'm sorry for taking so long to reply. Anyway I hope to help you as soon as possible if you'll encounter new issues!
Greetings!
